# Generated by Django 4.2.16 on 2026-02-10 09:43

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(choices=[('User', 'User'), ('CyberUser', 'CyberUser'), ('Admin', 'Admin'), ('SuperAdmin', 'SuperAdmin')], default='User', help_text="User's functional role in the system", max_length=20)),
                ('rank', models.CharField(blank=True, max_length=50, null=True)),
                ('social_media', models.BooleanField(default=False, help_text='Access to social media features')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when user was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when user was last updated')),
                ('is_void', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name of the news source', max_length=200)),
                ('url', models.URLField(help_text='Full TikTok or official URL', max_length=500)),
                ('image', models.ImageField(blank=True, help_text='Logo or favicon (optional)', null=True, upload_to='threat_alerts/source')),
            ],
            options={
                'verbose_name': 'News Source',
                'verbose_name_plural': 'News Sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, unique=True)),
                ('source_department', models.CharField(max_length=100)),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Search'), ('searching', 'Searching'), ('found', 'Information Found'), ('not_found', 'No Information Found'), ('error', 'Search Error')], default='pending', max_length=20)),
                ('search_date', models.DateTimeField(blank=True, null=True)),
                ('personnel_no', models.CharField(blank=True, max_length=50)),
                ('rank', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('unit', models.CharField(blank=True, max_length=200)),
                ('user_id', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='social_media/', verbose_name='Uploaded Photo')),
                ('photo_one', models.ImageField(blank=True, null=True, upload_to='social_media/', verbose_name='Uploaded Photo 1')),
                ('photo_two', models.ImageField(blank=True, null=True, upload_to='social_media/', verbose_name='Uploaded Photo 2')),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('response_sent', models.BooleanField(default=False)),
                ('platform', models.CharField(blank=True, max_length=50, verbose_name='Social Media Platform')),
            ],
            options={
                'verbose_name': 'Social Media URL Tracking',
                'ordering': ['-submitted_date'],
            },
        ),
        migrations.CreateModel(
            name='ThreatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the threat category', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is active and visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Threat Category',
                'verbose_name_plural': 'Threat Categories',
                'ordering': ['name'],
                'unique_together': {('name', 'created_by')},
            },
        ),
        migrations.CreateModel(
            name='ThreatAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='threat_alerts/')),
                ('video', models.FileField(blank=True, help_text='Upload video files', null=True, upload_to='threat_alerts/videos/')),
                ('province', models.CharField(blank=True, choices=[('koshi', 'Koshi'), ('madhesh', 'Madhesh'), ('bagmati', 'Bagmati'), ('gandaki', 'Gandaki'), ('lumbini', 'Lumbini'), ('karnali', 'Karnali'), ('sudurpaschim', 'Sudurpaschim')], help_text='Province where activity took place', max_length=50, null=True)),
                ('content', models.TextField()),
                ('source', models.CharField(default='unknown', max_length=50)),
                ('url', models.URLField(unique=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likes_count', models.IntegerField(default=0)),
                ('unlikes_count', models.IntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, help_text='Select threat category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='collect.threatcategory')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this alert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alerts', to=settings.AUTH_USER_MODEL)),
                ('users_liked', models.ManyToManyField(blank=True, help_text='Users who liked this alert', related_name='liked_alerts', to=settings.AUTH_USER_MODEL)),
                ('users_unliked', models.ManyToManyField(blank=True, help_text='Users who unliked this alert', related_name='unliked_alerts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SharedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Filename')),
                ('file', models.FileField(upload_to='shared_files/%Y/%m/%d/', verbose_name='File')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='Size (bytes)')),
                ('extension', models.CharField(blank=True, max_length=10, verbose_name='File Extension')),
                ('is_public', models.BooleanField(default=False, verbose_name='Public File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Download Count')),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_files', to=settings.AUTH_USER_MODEL, verbose_name='Shared With')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Shared File',
                'verbose_name_plural': 'Shared Files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MapMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('military_deployment', '🚨 Military Deployment'), ('protest', '✊ Protest/Rally'), ('violence_clash', '⚔️ Violence/Clash'), ('political_rally', '🏛️ Political Rally'), ('speech_event', '🎤 Political Speech'), ('other', '📌 Other Incident')], default='general', max_length=20)),
                ('color', models.CharField(choices=[('#FF0000', 'Red'), ('#0000FF', 'Blue'), ('#008000', 'Green'), ('#FFA500', 'Orange'), ('#800080', 'Purple'), ('#FFFF00', 'Yellow')], default='#FF0000', max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CurrentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing', models.CharField(help_text='When the activity took place', max_length=255)),
                ('location', models.CharField(help_text='Where the activity took place', max_length=255)),
                ('leader', models.CharField(help_text='Name of the person in charge', max_length=255)),
                ('number', models.CharField(blank=True, help_text='Contact number, ID, or team number', max_length=50, null=True)),
                ('vehicle', models.CharField(blank=True, help_text='Type of vehicle used (e.g., Toyota Hilux, Motorcycle)', max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='Details of the activity or event', null=True)),
                ('province', models.CharField(blank=True, choices=[('koshi', 'Koshi'), ('madhesh', 'Madhesh'), ('bagmati', 'Bagmati'), ('gandaki', 'Gandaki'), ('lumbini', 'Lumbini'), ('karnali', 'Karnali'), ('sudurpaschim', 'Sudurpaschim')], help_text='Province where activity took place', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_informations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DangerousKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, help_text='The dangerous keyword or phrase', max_length=100)),
                ('category', models.CharField(db_index=True, help_text='Category (e.g., Violence, Threats, Dehumanizing, etc.)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this keyword is active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dangerous Keyword',
                'verbose_name_plural': 'Dangerous Keywords',
                'ordering': ['word'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='collect_dan_categor_f2a6a9_idx'), models.Index(fields=['word'], name='collect_dan_word_b922c1_idx')],
                'unique_together': {('word', 'category')},
            },
        ),
        migrations.CreateModel(
            name='AutoNewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField()),
                ('url', models.URLField(max_length=1000)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('source', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=20)),
                ('content_length', models.IntegerField(default=0)),
                ('priority', models.CharField(default='medium', max_length=10)),
                ('threat_level', models.CharField(default='low', max_length=10)),
                ('keywords', models.TextField(blank=True)),
                ('categories', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_news_articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('url', 'created_by')},
            },
        ),
    ]
